#URL de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/tienda_db

#Credenciales
spring.datasource.username=postgres
spring.datasource.password=198115

#Driver para que Java sepa hablar con Postgres
spring.datasource.driver-class-name=org.postgresql.Driver

#Magia de JPA: "update" crea las tablas si no existen o las actualiza si agregamos campos
spring.jpa.hibernate.ddl-auto=create-drop

#Para que veas en la consola qué está haciendo JPA "por detrás"
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true